
server:
  port: 8090
spring:



  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver


    password: ENC(3F1eltMp3xhu5T+HyPoTIg==)
    url: ENC(Sop4X6qZnES4rPtOOytaLW2G/Wl22e86XygKZuMFt3U84ZdYNu35NTcSS+Nom+hj2/WcvUccki4j4u4jQ1OI1KzhoysRpcZLKWPlQH4nW9+JbUmY1FF9MWXrbDtCq+Dq2n0+zvPrG0U=)
    username: ENC(tJcVF6BtGG3Tn29MBGMYig==)
#  

  jpa:
    database: mysql
    database-platform: ENC(voUvSc5bHsIEKBvrSNAQx5mIJZSJD+khDpFMhSABjivmijlczwEdhA3R4Y3wopxvhvwDUNNstOQ=)
    generate-ddl: true

    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
      
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    







server:
  port: 8090
spring:



  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver


    password: 1234

    url: jdbc:mysql://localhost:3308/vono?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
#  

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true

    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
      







 